name: CI_CD_Pipeline

on:
  push: [main, master]
  pull: [main, master]
  workflow_dispatch:



jobs:
  CI_push:
    if: github.event_name == 'push'

    run-on: ubuntu-latest
    defaults:
    run:
      working-directory: frontend

    steps:

      - name: chackout code
        uses: actions/checkout@v4

      - name: set-up Node jobs
        uses: actions/setup-node@v4
        with: 
          node-version: '21'

      - name: install all dependency
        run: npm install

      - name: build project
        if: github.event_name == 'push'
        run: npm run build

      - name: Upload the build file to artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: frontend/Deploy/

      


  CD_Push:
    
    needs: CI_push
    if: github.event_name == 'push' && needs.CI_push.result == 'success'
    run-on: ubuntu-latest

    steps:

      - name: checkout code
        uses: actions@checkout@v4


      - name: setup Node js
        uses: actions/setup-node@v4
        with:
          node-version: '21'


      - name: Download artifact from CI_push
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./frontend/Deploy/


      - name: build file checkout
        run: ls -la ./frontend/Deploy


      - name: Deploying to Vercel
        run: echo "🚀Deploying the project"

